bitcoin:
  provider: ""
  username: ""
  password: ""

evm_providers:
  - name: "bfc-testnet"
    id: 49088
    provider: ""
    interval: 2000
    is_native: true
  - name: "eth-goerli"
    id: 5
    provider: ""
    interval: 5000
  - name: "bsc-testnet"
    id: 97
    provider: ""
    interval: 2000
  - name: "matic-mumbai"
    id: 80001
    provider: ""
    interval: 1000

handler_configs:
  - handler_type: Socket
    watch_list:
      - chain_id: 49088
        contract: "0x0218371b18340aBD460961bdF3Bd5F01858dAB53"
      - chain_id: 5
        contract: "0xeF5260Db045200142a6B5DDB297e860099ffd51d"
      - chain_id: 97
        contract: "0x8039c3AD8ED55509fD3f6Daa78867923fDe6E61c"
      - chain_id: 80001
        contract: "0xA25357F3C313Bd13885678f935178211f0dF6722"
  - handler_type: Vault
    watch_list:
      - chain_id: 49088
        contract: "0x90381bB369D4F8069fdA9246b23637a78c5d1c83"
      - chain_id: 5
        contract: "0x7EB02c73349B3De1406e6b433c5bA1a526CBF253"
      - chain_id: 97
        contract: "0x27C66cb5caa07C9B332939c357c789C606f5054C"
      - chain_id: 80001
        contract: "0xB2ba0020560cF6c164DC48D1E29559AbA8472208"

mnemonic: ""

offchain_configs:
  oracle_price_feeder:
    - network_id: 49088
      feed_interval: 300
      contract: "0x0218371b18340aBD460961bdF3Bd5F01858dAB53"
      price_sources: [ Coingecko ]
      symbols: [ "ETH", "BFC", "BNB", "MATIC", "USDC", "BIFI" ]
